module.exports = [
  // ========================= BOURSES =========================
  {
    type: "Bourse",
    titre: "Bourse Master Informatique",
    description: "Bourse complète pour étudiants en informatique.",
    image: "https://picsum.photos/400/200",
    logo: "https://picsum.photos/100",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Université Paris Saclay",
    orgDescription: "Grande université française",
    eligibility: "Licence en informatique",
    benefits: "Frais + logement",
    language: "French",
    Duration: "2 ans",
    filiere: "Informatique",
    niveau_academique: "Master",
    montant: 15000,
    dateDebut: new Date("2026-09-01"),
    dateLimite: new Date("2026-05-30"),
    pays: "France"
  },
  {
    type: "Bourse",
    titre: "Bourse Doctorat IA",
    description: "Programme doctoral en intelligence artificielle.",
    image: "https://picsum.photos/400/201",
    logo: "https://picsum.photos/101",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "MIT",
    orgDescription: "Université de recherche",
    eligibility: "Master en IA",
    benefits: "Salaire + logement",
    language: "English",
    Duration: "3 ans",
    filiere: "Intelligence Artificielle",
    niveau_academique: "Doctorat",
    montant: 45000,
    dateDebut: new Date("2026-10-01"),
    dateLimite: new Date("2026-06-15"),
    pays: "USA"
  },

  // ========================= EVENEMENTS =========================
  {
    type: "Evenement",
    titre: "Web Dev Conference 2026",
    description: "Conférence internationale de développement web.",
    image: "https://picsum.photos/400/202",
    logo: "https://picsum.photos/102",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Web Global",
    orgDescription: "Organisation tech",
    eligibility: "Ouvert à tous",
    benefits: "Certificat & networking",
    language: "English",
    Duration: "3 jours",
    filiere: "Web Development",
    dateDebut: new Date("2026-04-10"),
    dateLimite: new Date("2026-04-10"),
    pays: "Germany",
    lieu: "Berlin"
  },
  {
    type: "Evenement",
    titre: "Game Dev Expo",
    description: "Salon dédié à la création de jeux vidéo.",
    image: "https://source.unsplash.com/800x600/?videogame",
    logo: "https://source.unsplash.com/200x200/?joystick",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Indie Games Collective",
    orgDescription: "Association de studios indépendants",
    eligibility: "Passionnés de jeux",
    benefits: "Playtests & Recrutement",
    language: "English",
    Duration: "4 jours",
    filiere: "Game Development",
    dateDebut: new Date("2026-11-10"),
    dateLimite: new Date("2026-11-01"),
    pays: "USA",
    lieu: "San Francisco"
  },

  // ========================= FORMATIONS =========================
  {
    type: "Formation",
    titre: "Formation React JS",
    description: "Formation complète React pour débutants.",
    image: "https://source.unsplash.com/800x600/?reactjs",
    logo: "https://source.unsplash.com/200x200/?education",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "OpenClassrooms",
    orgDescription: "Plateforme e-learning",
    eligibility: "Débutants",
    benefits: "Certificat",
    language: "French",
    Duration: "8 semaines",
    filiere: "Web Development",
    montant: 0,
    mode_apprentissage: "distance",
    statut_financier: "free",
    dateDebut: new Date("2026-03-01"),
    dateLimite: new Date("2026-02-20"),
    pays: "Online"
  },
  {
    type: "Formation",
    titre: "Bootcamp DevOps & Cloud",
    description: "Formation intensive DevOps et cloud computing.",
    image: "https://source.unsplash.com/800x600/?devops",
    logo: "https://source.unsplash.com/200x200/?cloud",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Cloud Academy",
    orgDescription: "Experts en cloud",
    eligibility: "Développeurs expérimentés",
    benefits: "Certification",
    language: "English",
    Duration: "10 semaines",
    filiere: "DevOps",
    montant: 1800,
    mode_apprentissage: "presentiel",
    statut_financier: "paid",
    dateDebut: new Date("2026-02-10"),
    dateLimite: new Date("2026-02-01"),
    pays: "UK"
  },
  // ========================= BOURSES =========================
  {
    type: "Bourse",
    titre: "Bourse Master Data Science",
    description: "Programme de bourse pour étudiants en science des données.",
    image: "https://source.unsplash.com/800x400/?datascience",
    logo: "https://source.unsplash.com/200x200/?university",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Université de Toronto",
    orgDescription: "Institution canadienne de recherche",
    eligibility: "Licence en mathématiques, informatique ou statistique",
    benefits: "Frais de scolarité + allocation mensuelle",
    language: "English",
    Duration: "2 ans",
    filiere: "Data Science",
    niveau_academique: "Master",
    montant: 20000,
    dateDebut: new Date("2026-09-15"),
    dateLimite: new Date("2026-05-31"),
    pays: "Canada"
  },
  {
    type: "Bourse",
    titre: "Bourse Erasmus+ Mobilité",
    description: "Programme de mobilité européenne pour étudiants en ingénierie.",
    image: "https://source.unsplash.com/800x400/?europe,students",
    logo: "https://source.unsplash.com/200x200/?erasmus",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Commission Européenne",
    orgDescription: "Programme d'éducation et de mobilité",
    eligibility: "Inscription dans une université européenne",
    benefits: "Frais de voyage + allocation mensuelle",
    language: "Multilingue",
    Duration: "6 mois",
    filiere: "Engineering",
    niveau_academique: "Licence",
    montant: 8000,
    dateDebut: new Date("2026-02-01"),
    dateLimite: new Date("2025-12-15"),
    pays: "Europe"
  },

  // ========================= EVENEMENTS =========================
  {
    type: "Evenement",
    titre: "AI Summit 2026",
    description: "Sommet mondial sur l'intelligence artificielle et ses applications.",
    image: "https://source.unsplash.com/800x400/?artificialintelligence,conference",
    logo: "https://source.unsplash.com/200x200/?ai",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "AI Global Forum",
    orgDescription: "Organisation internationale dédiée à l'IA",
    eligibility: "Professionnels et étudiants en IA",
    benefits: "Networking, ateliers pratiques, certificats",
    language: "English",
    Duration: "5 jours",
    filiere: "Artificial Intelligence",
    dateDebut: new Date("2026-01-19"),
    dateLimite: new Date("2026-07-01"),
    pays: "Japan",
    lieu: "Tokyo"
  },
  {
    type: "Evenement",
    titre: "Cybersecurity World Congress",
    description: "Congrès international sur la cybersécurité et la protection des données.",
    image: "https://source.unsplash.com/800x400/?cybersecurity,conference",
    logo: "https://source.unsplash.com/200x200/?security",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "CyberSec Alliance",
    orgDescription: "Réseau mondial de cybersécurité",
    eligibility: "Ouvert aux professionnels et étudiants",
    benefits: "Conférences, certifications, opportunités de carrière",
    language: "English",
    Duration: "3 jours",
    filiere: "Cybersecurity",
    dateDebut: new Date("2026-01-18"),
    dateLimite: new Date("2026-04-20"),
    pays: "Spain",
    lieu: "Barcelona"
  },

  // ========================= FORMATIONS =========================
  {
    type: "Formation",
    titre: "Formation Python Data Analysis",
    description: "Cours intensif sur l'analyse de données avec Python.",
    image: "https://source.unsplash.com/800x400/?python,code",
    logo: "https://source.unsplash.com/200x200/?data",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "DataCamp",
    orgDescription: "Plateforme spécialisée en data science",
    eligibility: "Débutants et intermédiaires",
    benefits: "Certificat reconnu",
    language: "English",
    Duration: "6 semaines",
    filiere: "Data Analysis",
    montant: 300,
    mode_apprentissage: "distance",
    statut_financier: "paid",
    dateDebut: new Date("2026-01-18"),
    dateLimite: new Date("2026-03-01"),
    pays: "Online"
  },
  {
    type: "Formation",
    titre: "UX/UI Design Bootcamp",
    description: "Programme intensif pour devenir designer UX/UI.",
    image: "https://source.unsplash.com/800x400/?ux,design",
    logo: "https://source.unsplash.com/200x200/?ui",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Design Academy",
    orgDescription: "École spécialisée en design numérique",
    eligibility: "Étudiants et professionnels créatifs",
    benefits: "Portfolio + certification",
    language: "French",
    Duration: "12 semaines",
    filiere: "UX/UI Design",
    montant: 1200,
    mode_apprentissage: "presentiel",
    statut_financier: "paid",
    dateDebut: new Date("2026-01-19"),
    dateLimite: new Date("2026-05-15"),
    pays: "France"
  },
    // ========================= BOURSES =========================
    {
      type: "Bourse",
      titre: "Bourse Master Cybersécurité",
      description: "Programme de bourse pour étudiants en cybersécurité.",
      image: "https://source.unsplash.com/800x400/?cybersecurity,student",
      logo: "https://source.unsplash.com/200x200/?shield",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Université de Lausanne",
      orgDescription: "Université suisse reconnue pour ses recherches",
      eligibility: "Licence en informatique ou sécurité",
      benefits: "Frais de scolarité + logement",
      language: "French",
      Duration: "2 ans",
      filiere: "Cybersecurity",
      niveau_academique: "Master",
      montant: 18000,
      dateDebut: new Date("2026-09-01"),
      dateLimite: new Date("2026-05-15"),
      pays: "Switzerland"
    },
    {
      type: "Bourse",
      titre: "Bourse Doctorat Robotique",
      description: "Programme doctoral en robotique avancée.",
      image: "https://source.unsplash.com/800x400/?robotics,lab",
      logo: "https://source.unsplash.com/200x200/?robot",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Carnegie Mellon University",
      orgDescription: "Université américaine spécialisée en robotique",
      eligibility: "Master en ingénierie ou IA",
      benefits: "Salaire + frais de recherche",
      language: "English",
      Duration: "4 ans",
      filiere: "Robotics",
      niveau_academique: "Doctorat",
      montant: 50000,
      dateDebut: new Date("2026-10-01"),
      dateLimite: new Date("2026-06-30"),
      pays: "USA"
    },
  
    // ========================= EVENEMENTS =========================
    {
      type: "Evenement",
      titre: "Blockchain Summit 2026",
      description: "Conférence internationale sur la blockchain et les cryptomonnaies.",
      image: "https://source.unsplash.com/800x400/?blockchain,conference",
      logo: "https://source.unsplash.com/200x200/?bitcoin",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Blockchain Europe",
      orgDescription: "Organisation dédiée aux technologies décentralisées",
      eligibility: "Ouvert aux professionnels et étudiants",
      benefits: "Networking, ateliers, certificats",
      language: "English",
      Duration: "3 jours",
      filiere: "Blockchain",
      dateDebut: new Date("2026-05-12"),
      dateLimite: new Date("2026-04-25"),
      pays: "Netherlands",
      lieu: "Amsterdam"
    },
    {
      type: "Evenement",
      titre: "VR & AR Expo",
      description: "Salon mondial dédié à la réalité virtuelle et augmentée.",
      image: "https://source.unsplash.com/800x400/?virtualreality,expo",
      logo: "https://source.unsplash.com/200x200/?vr",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Immersive Tech Group",
      orgDescription: "Collectif spécialisé en technologies immersives",
      eligibility: "Ouvert à tous",
      benefits: "Démonstrations, recrutements, certificats",
      language: "English",
      Duration: "4 jours",
      filiere: "VR/AR",
      dateDebut: new Date("2026-08-18"),
      dateLimite: new Date("2026-08-01"),
      pays: "USA",
      lieu: "Los Angeles"
    },
  
    // ========================= FORMATIONS =========================
    {
      type: "Formation",
      titre: "Formation Machine Learning",
      description: "Cours complet sur les bases et applications du machine learning.",
      image: "https://source.unsplash.com/800x400/?machinelearning,education",
      logo: "https://source.unsplash.com/200x200/?ml",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Coursera",
      orgDescription: "Plateforme mondiale d’e-learning",
      eligibility: "Débutants et intermédiaires",
      benefits: "Certificat reconnu",
      language: "English",
      Duration: "10 semaines",
      filiere: "Machine Learning",
      montant: 400,
      mode_apprentissage: "distance",
      statut_financier: "paid",
      dateDebut: new Date("2026-04-01"),
      dateLimite: new Date("2026-03-20"),
      pays: "Online"
    },
    {
      type: "Formation",
      titre: "Formation Développement Full Stack",
      description: "Bootcamp intensif pour devenir développeur full stack.",
      image: "https://source.unsplash.com/800x400/?coding,developer",
      logo: "https://source.unsplash.com/200x200/?code",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Le Wagon",
      orgDescription: "École de code internationale",
      eligibility: "Débutants motivés",
      benefits: "Portfolio + certification",
      language: "French",
      Duration: "9 semaines",
      filiere: "Web Development",
      montant: 2500,
      mode_apprentissage: "presentiel",
      statut_financier: "paid",
      dateDebut: new Date("2026-07-05"),
      dateLimite: new Date("2026-06-15"),
      pays: "France"
    }
,
  // ========================= BOURSES =========================
  {
    type: "Bourse",
    titre: "Bourse Master Informatique",
    description: "Bourse complète pour étudiants en informatique.",
    image: "https://picsum.photos/400/200",
    logo: "https://picsum.photos/100",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Université Paris Saclay",
    orgDescription: "Grande université française",
    eligibility: "Licence en informatique",
    benefits: "Frais + logement",
    language: "French",
    Duration: "2 ans",
    filiere: "Informatique",
    niveau_academique: "Master",
    montant: 15000,
    dateDebut: new Date("2026-01-20"), // thisWeek
    dateLimite: new Date("2026-05-30"),
    pays: "France"
  },
  {
    type: "Bourse",
    titre: "Bourse Doctorat IA",
    description: "Programme doctoral en intelligence artificielle.",
    image: "https://picsum.photos/400/201",
    logo: "https://picsum.photos/101",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "MIT",
    orgDescription: "Université de recherche",
    eligibility: "Master en IA",
    benefits: "Salaire + logement",
    language: "English",
    Duration: "3 ans",
    filiere: "Intelligence Artificielle",
    niveau_academique: "Doctorat",
    montant: 45000,
    dateDebut: new Date("2026-02-10"), // nextMonth
    dateLimite: new Date("2026-06-15"),
    pays: "USA"
  },
  {
    type: "Bourse",
    titre: "Bourse Master Data Science",
    description: "Programme de bourse pour étudiants en science des données.",
    image: "https://source.unsplash.com/800x400/?datascience",
    logo: "https://source.unsplash.com/200x200/?university",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Université de Toronto",
    orgDescription: "Institution canadienne de recherche",
    eligibility: "Licence en mathématiques, informatique ou statistique",
    benefits: "Frais de scolarité + allocation mensuelle",
    language: "English",
    Duration: "2 ans",
    filiere: "Data Science",
    niveau_academique: "Master",
    montant: 20000,
    dateDebut: new Date("2026-01-22"), // thisWeek
    dateLimite: new Date("2026-05-31"),
    pays: "Canada"
  },
  {
    type: "Bourse",
    titre: "Bourse Erasmus+ Mobilité",
    description: "Programme de mobilité européenne pour étudiants en ingénierie.",
    image: "https://source.unsplash.com/800x400/?europe,students",
    logo: "https://source.unsplash.com/200x200/?erasmus",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Commission Européenne",
    orgDescription: "Programme d'éducation et de mobilité",
    eligibility: "Inscription dans une université européenne",
    benefits: "Frais de voyage + allocation mensuelle",
    language: "Multilingue",
    Duration: "6 mois",
    filiere: "Engineering",
    niveau_academique: "Licence",
    montant: 8000,
    dateDebut: new Date("2026-02-01"), // nextMonth
    dateLimite: new Date("2025-12-15"),
    pays: "Europe"
  },
  {
    type: "Bourse",
    titre: "Bourse Master Cybersécurité",
    description: "Programme de bourse pour étudiants en cybersécurité.",
    image: "https://source.unsplash.com/800x400/?cybersecurity,student",
    logo: "https://source.unsplash.com/200x200/?shield",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Université de Lausanne",
    orgDescription: "Université suisse reconnue pour ses recherches",
    eligibility: "Licence en informatique ou sécurité",
    benefits: "Frais de scolarité + logement",
    language: "French",
    Duration: "2 ans",
    filiere: "Cybersecurity",
    niveau_academique: "Master",
    montant: 18000,
    dateDebut: new Date("2026-01-19"), // thisWeek
    dateLimite: new Date("2026-05-15"),
    pays: "Switzerland"
  },
  {
    type: "Bourse",
    titre: "Bourse Doctorat Robotique",
    description: "Programme doctoral en robotique avancée.",
    image: "https://source.unsplash.com/800x400/?robotics,lab",
    logo: "https://source.unsplash.com/200x200/?robot",
    lienSource: "#",
    lienOrganisation: "#",
    organisme: "Carnegie Mellon University",
    orgDescription: "Université américaine spécialisée en robotique",
    eligibility: "Master en ingénierie ou IA",
    benefits: "Salaire + frais de recherche",
    language: "English",
    Duration: "4 ans",
    filiere: "Robotics",
    niveau_academique: "Doctorat",
    montant: 50000,
    dateDebut: new Date("2026-02-18"), // nextMonth
    dateLimite: new Date("2026-06-30"),
    pays: "USA"
  }
];

  

